//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso_FAS_Testing
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class FormTestCoded : WebTest
    {

        public FormTestCoded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            foreach (var request in new TestFunction(1).TestRequests)
            {
                yield return request;
            }


            //yield return new TestRequest("http://contoso-fas/Web/home.aspx");

            //yield return new TestRequest("http://contoso-fas/Web/login.aspx", "http://contoso-fas/Web/Home.aspx");

            //yield return new TestRequest("http://contoso-fas/WebServices/Authentication/Login",
            //    "",
            //    "{\"user\":\"gpburdell\",\"password\":\"foo\"}",
            //    new List<ExtractionRule>()
            //    {
            //        new CustomExtractText("\"Token\":\"", "\"", "LoginToken")
            //    });

            //yield return new TestRequest("http://contoso-fas/Web/appmain.aspx?token={{LoginToken}}", "http://contoso-fas/Web/Home.aspx");

            //yield return new TestRequest("http://localhost:50274/Default.aspx?firstName=Kevin&lastName=Tuttle&email=ktuttle@ivision.com&submit=",
            //    "http://localhost:50274/",
            //    new List<ExtractionRule>()
            //    {
            //        new CustomExtractText("First: ", "<br/>", "FirstName"),
            //        new CustomExtractText("Last: ", "<br/>", "LastName"),
            //        new CustomExtractText("Email: ", "<br/>", "Email")
            //    });
        }
    }
}
